name = "AoCElfTools"
uuid = "d9c9bf20-ca78-4ff2-99ab-ea0dd0f9def8"
authors = ["Patrick Bouffard and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
